### ISSUE TITLE
My iPhone XR dose not detect

### ISSUE THREAD

**Issue by msaus** [RemoteDebug/remotedebug-ios-webkit-adapter#156] opened 2019-06-21 08:50 UTC
Hello there,

I have iPhone XR and the iOS version is 12.3.1 that is the latest one.

iPhone 7 is okay, but, iPhone XR cannot be detected.

Also, I updated iTunes today.

Do you have any idea for this?

**Comment by Jaycexx** [comment] 2019-06-27 10:44
my XR cannot be detected too.

**Comment by git-antonyuk** [comment] 2019-06-30 20:55
Same bug on XR / X. No remote target detected. On 8+ works

**Comment by ghost** [comment] 2019-07-03 10:11
Hi, 
Look at https://github.com/fishbone1/remotedebug-ios-webkit-adapter, our Friend made a fix for this situation- works fine with my iPhone X.

**Comment by scottbram** [comment] 2019-11-15 22:04
> Hi,
> Look at https://github.com/fishbone1/remotedebug-ios-webkit-adapter, our Friend made a fix for this situation- works fine with my iPhone X.

Will they be doing a PR to get their solution into the main project?

**Comment by ewanharris** [comment] 2020-01-02 14:07
Based off the comments, I believe this to be a duplicate of #138. Please open a new issue if the issue still persists when using the latest prerelease, which can be obtained via `npm i -g remotedebug-ios-webkit-adapter@next`

**Closed as completed by ewanharris** 2020-01-02 14:07 UTC
