### ISSUE TITLE
Chrome DevTools empty

### ISSUE THREAD

**Issue by kalle153** [RemoteDebug/remotedebug-ios-webkit-adapter#151] opened 2019-06-11 12:42 UTC
Hi guys,

I went through the complete installation. Everthing fine so far. The device shows up properly, but after opening the "inspect" window, everthing is blanc.

![chrome_empty](https://user-images.githubusercontent.com/17186492/59272722-ef37d300-8c56-11e9-93b5-0799eb940b7c.png)

The Powershell shows:
~~~~
  PS C:\WINDOWS\system32> remotedebug_ios_webkit_adapter --port=9000
  remotedebug-ios-webkit-adapter is listening on port 9000
  iosAdapter.getTargets
  iosAdapter.getTargets
  New websocket connection to /ios_00008020-000D25661A88002E/ws://127.0.0.1:9101/devtools/page/1
  Connection established to ws://127.0.0.1:9101/devtools/page/1
  (node:6108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): #<Object>
  (node:6108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  (node:6108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): #<Object>
  (node:6108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): #<Object>
  (node:6108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): #<Object>
  (node:6108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): #<Object>
  iosAdapter.getTargets
~~~~

Is there anything I can do about it? I'm using iOS 12.3.1 and latest versions of iTunes, Chrome, webkit-adapter and debug-proxy

Thanks for the support!

**Comment by Us3rNaMeD** [comment] 2019-06-11 12:50
I'd like to refer you to https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/138

**Comment by kalle153** [comment] 2019-06-24 20:37
You were right.

https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/138#issuecomment-493233795
This comment solved it for me.

**Comment by munrocket** [comment] 2019-10-22 10:25
MANUAL HOW TO RUN [remotedebug-ios-webkit-adapter](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter) on Linux/Windows with iOS 12.2+

* Follow Step 1 from the readme
* Instead of following Step 2 from the readme, download the code from [here](https://github.com/arseneyr/remotedebug-ios-webkit-adapter/tree/ios12.2) as described in this [issue](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/138#issuecomment-493324681)
* Make sure you are using node 11 instead of 12 or the next step will fail. (`nvm install 11 && node -v`)
* In downloaded remotedebug-ios-webkit-adapter directory update typescript and typemoq (`npm i typescript@3.5.3 && npm i typemoq@2.1.0`, )
* Run `npm install`, `npm build` and `npm start` with conected iPhone
* Continue onto Step 3 from the readme

Also worth noting that chrome://inspect doesn't scan port 9000 by-default so you need to add localhost:9000 using the Configure button.

**Comment by ewanharris** [comment] 2020-01-02 14:07
I believe this to be a duplicate of #138. Please open a new issue if the issue still persists when using the latest prerelease, which can be obtained via `npm i -g remotedebug-ios-webkit-adapter@next`

**Closed as completed by ewanharris** 2020-01-02 14:07 UTC
