### ISSUE TITLE
Windows: Unable to find devices

### ISSUE THREAD

**Issue by CWBudde** [RemoteDebug/remotedebug-ios-webkit-adapter#44] opened 2017-01-23 13:50 UTC
I think I have installed the adapter (and everything that is required to run it) as mentioned. However, I fail to list the devices in the chrome devtool (and firefox).

The list does not even show up. It stays empty and does not even list the very own browser tabs.

This said I do get some warnings and now I wonder whether these are related:

C:\>remotedebug_ios_webkit_adapter --port=9222
adapter.start
remotedebug-ios-webkit-adapter is listening on port 9222
iosAdapter.getTargets
http://127.0.0.1:9222/json
(node:6040) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 18): TypeError: Bad argument
(node:6040) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not hand
led will terminate the Node.js process with a non-zero exit code.chrome-devtools://devtools/bundled/inspector.html

**Comment by auchenberg** [comment] 2017-01-23 21:25
Aha. Do you see a more detailed stack trace when it's crashing @CWBudde ?

**Comment by CWBudde** [comment] 2017-01-23 21:37
Not really. The devtools device list stays completely empty until I cancel (CTRL+c) the adapter. After that it fills nearly instantly. At one point it even crashed Chrome.

As an interesting side node: After I cancel it, it even shows taps for inspection that are located in another chromium based browser (with remote debugging port 9000), which I could not see prior to this. Maybe this is related and that other browser (which I use for testing) is interupting the process

**Comment by auchenberg** [comment] 2017-01-23 21:43
Yeah, it seems like theres an unhandled exception the adapter, which means the devices won't show up inside Chrome, etc.

The listing of devices inside chrome://inspect is a Chromium thing, and not something I control from the adapter.

**Comment by CWBudde** [comment] 2017-01-23 21:48
Is there anything I can do to help you (e.g. run the adapter in some sort of debug mode to give you some more hints about the problem)?

**Comment by auchenberg** [comment] 2017-01-23 21:55
The adapter is still pretty young (and not publicly released for this reason), so it doesn't have a debug mode yet.

What devices are you using? 
What platform?
Node version?

**Comment by CWBudde** [comment] 2017-01-23 22:03
Device: iPad mini 4 with iOS 10.2 (I could test other devices from our lab, but not today anymore)
Platform: Win64
Node: 7.4.0 (didn't work with 7.3.0 either)

I tested it with Chrome 55.0.2883.87 and Firefox 50.1.0, both with the same problems. I even reinstalled iTunes to see if this caused the problem.

**Comment by auchenberg** [comment] 2017-01-23 23:07
Aha, it might be an iOS10 issue, as the bundled version of `ios-webkit-debug-proxy` might be too old to have iOS 10 support.

Can you try to download the HEAD release of https://github.com/artygus/ios-webkit-debug-proxy-win32, and replace the binary inside `node_modules/node_modules/vs-libimobile/lib/`?

**Comment by CWBudde** [comment] 2017-01-24 11:02
I have tried both the 32-bit version (a release from 2015, far before iOS 10 was introduced) and the one from november 2016 (is equal to the last commit date).
In order to replace the previously existing properly I had to rename the file from ios_webkit_debug_proxy to ios-webkit-debug-proxy.

Running the old executable standalone resulted in a crash, but the new executable seems to run and find my iPad properly. This said the error message stays the same and chrome isn't able to list any devices, again.

**Comment by auchenberg** [comment] 2017-01-24 23:18
Alright, I'll try to see if I can debug it further during this week.

**Comment by CWBudde** [comment] 2017-01-25 00:00
Thanks

**Comment by paulirish** [comment] 2017-02-24 09:37
`node --trace-warnings  out/index.js` should give you a stack trace for that unhandled rejection.

**Comment by CWBudde** [comment] 2017-03-12 12:27
Here's what it reads:

```
iosAdapter.getTargets
http://127.0.0.1:9222/json
(node:8696) TypeError: Bad argument
    at ChildProcess.spawn (internal/child_process.js:294:26)
    at exports.spawn (child_process.js:386:9)
    at Object.exports.execFile (child_process.js:149:15)
    at A:\remotedebug-ios-webkit-adapter\out\adapters\iosAdapter.js:174:29
    at IOSAdapter.getDeviceVersion (A:\remotedebug-ios-webkit-adapter\out\adapters\iosAdapter.js:172:16)
    at A:\remotedebug-ios-webkit-adapter\out\adapters\iosAdapter.js:54:36
    at Array.forEach (native)
    at A:\remotedebug-ios-webkit-adapter\out\adapters\iosAdapter.js:47:21
    at process._tickCallback (internal/process/next_tick.js:109:7)
(node:8696) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not hand
led will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:69:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:86:11)
    at process._tickCallback (internal/process/next_tick.js:110:7)
```
I hope this helps.

**Comment by auchenberg** [comment] 2017-03-14 05:23
@CWBudde I haven't debugged this on my Windows machine yet, but think this is caused by a wrong path to `iDeviceInfo`, which is resolved in https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/blob/master/src/adapters/iosAdapter.ts#L182.

Can you debug, and see if the path exists?

**Comment by CWBudde** [comment] 2017-03-14 09:20
It now reads: 

remotedebug-ios-webkit-adapter failed to run { Error: ENOENT: no such file or directory, stat 'A:\node_modules\vs-libimobile\lib\ios_webkit_debug_proxy.exe'

when the file is in A:\remotedebug-ios-webkit-adapter\node_modules\vs-libimobile\lib\ios_webkit_debug_proxy.exe

It seems that there is one '../' too much somewhere.

If I copy the files manually to the wrong path it seems to work as expected, though.

**Closed as completed** 2017-03-14 20:25 UTC
Labels: bug
