### ISSUE TITLE
ios 12.4.4 

### ISSUE THREAD

**Issue by gerrardLT** [RemoteDebug/remotedebug-ios-webkit-adapter#178] opened 2019-12-30 07:38 UTC
I'm testing with an ios device on 12.4.4 and i can now see the pages in the chrome://inspect/#devices and open the inspector but nothing shows up,not even the URL.

When i click the inspect button,i get the information like this :"Lite mode isn't available for iPhones or iPads because of platform constraints. " I don't know what this means.Expect your response.

Thanks

**Comment by ewanharris** [comment] 2020-01-02 14:06
I believe this to be a duplicate of #138. Please open a new issue if the issue still persists when using the latest prerelease, which can be obtained via `npm i -g remotedebug-ios-webkit-adapter@next`

**Closed as completed by ewanharris** 2020-01-02 14:06 UTC
