### ISSUE TITLE
'Profiler' domain was not found

### ISSUE THREAD

**Issue by ideeeyut** [RemoteDebug/remotedebug-ios-webkit-adapter#133] opened 2019-02-20 16:32 UTC
## Environment: 
Ubuntu 16.04
iPad iOS Version: 12.1.1 or iPhone iOS Version: 12.1.2
Desktop Chrome Version: 72.0.3626.81

## Problem
I followed all the steps to set this up on Linux (building versions of libimobiledevice etc). It works successfully about half of the time. The other half of the time I click on the link in Chrome Dev Tools to inspect a page on the iOS device and the inspector window opens, the Remote Target link disappears and the web socket connection closes. When running DEBUG=remotedebug remotedebug-ios-webkit-adapter I get: 

`remotedebug sendToTools.{"error":{"code":-32601,"message":"'Profiler' domain was not found","data":[{"code":-32601,"message":"'Profiler' domain was not found"}]},"id":5} +708ms`

The related debug output is:

```
remotedebug adapterCollection.forwardTo, url=/ios_7591b2772d436bb0e621f993c11dc7e961f5f61c/ws://127.0.0.1:9323/devtools/page/1 +1ms
remotedebug adapterCollection.getWebSocketId, url=/ios_7591b2772d436bb0e621f993c11dc7e961f5f61c/ws://127.0.0.1:9323/devtools/page/1 +0ms
remotedebug adapter.forwardTo, targetId=ws://127.0.0.1:9323/devtools/page/1 +0ms
remotedebug sendToTarget.{"id":26,"method":"Page.setTouchEmulationEnabled","params":{"enabled":true,"configuration":"mobile"}} +1ms
remotedebug adapterCollection.forwardTo, url=/ios_7591b2772d436bb0e621f993c11dc7e961f5f61c/ws://127.0.0.1:9323/devtools/page/1 +0ms
remotedebug adapterCollection.getWebSocketId, url=/ios_7591b2772d436bb0e621f993c11dc7e961f5f61c/ws://127.0.0.1:9323/devtools/page/1 +1ms
remotedebug adapter.forwardTo, targetId=ws://127.0.0.1:9323/devtools/page/1 +0ms
remotedebug sendToTools.{"id":27,"result":{}} +0ms
remotedebug adapterCollection.forwardTo, url=/ios_7591b2772d436bb0e621f993c11dc7e961f5f61c/ws://127.0.0.1:9323/devtools/page/1 +1ms
remotedebug adapterCollection.getWebSocketId, url=/ios_7591b2772d436bb0e621f993c11dc7e961f5f61c/ws://127.0.0.1:9323/devtools/page/1 +0ms
remotedebug adapter.forwardTo, targetId=ws://127.0.0.1:9323/devtools/page/1 +0ms
remotedebug sendToTarget.{"id":28,"method":"Page.setTouchEmulationEnabled","params":{"enabled":false,"configuration":"desktop"}} +0ms
remotedebug adapterCollection.forwardTo, url=/ios_7591b2772d436bb0e621f993c11dc7e961f5f61c/ws://127.0.0.1:9323/devtools/page/1 +1ms
remotedebug adapterCollection.getWebSocketId, url=/ios_7591b2772d436bb0e621f993c11dc7e961f5f61c/ws://127.0.0.1:9323/devtools/page/1 +0ms
remotedebug adapter.forwardTo, targetId=ws://127.0.0.1:9323/devtools/page/1 +0ms
remotedebug sendToTarget.{"id":29,"method":"Runtime.runIfWaitingForDebugger"} +0ms
remotedebug sendToTools.{"result":{"frameTree":{"frame":{"id":"0.1","loaderId":"0.8","url":"http://dscott-workstation:81/#!/stage","mimeType":"text/html","securityOrigin":"http://dscott-workstation:81"},"resources":[{"url":"http://dscott-workstation:81/service/streams/16/frame?width=414&height=234&now=1550679278556","type":"Image","mimeType":"image/jpeg"},{"url":"http://dscott-workstation:81/service/streams/3/frame?width=414&height=234&now=1550679279209","type":"Image","mimeType":"image/jpeg"},{"url":"http://dscott-workstation:81/css/built-no-cache.css","type":"Stylesheet","mimeType":"text/css","sourceMapURL":"data:application/json;charset=utf8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImluZGV4LmNzcyIsImdsb2JhbHMuY3NzIiwic2VydmljZXMvQXV0b2NvbXBsZXRlUmVwYWlyLmNzcyIsImNvbXBvbmVudHMvYWN0aXZhdGlvbi9hY3RpdmF0aW9uLmNzcyIsImNvbXBvbmVudHMvYmFnL2JhZy5jc3MiLCJjb21wb25lbnRzL2JhZy9iYWdDYW1lcmFzLmNzcyIsImNvbXBvbmVudHMvYmFnL2NhbWVyYUdyb3VwLmNzcyIsImNvbXBvbmVudHMvY2FtZXJhR3JvdXBzL2NhbWVyYUdyb3VwQ29uZmlnLmNzcyIsImNvbXBvbmVudHMvY2FtZXJhR3JvdXBzL2NhbWVyYUdyb3VwVmlldy5jc3MiLCJjb21wb25lbnRzL2NoaXBzL ... cut for brevity ... tdGFibGUgdGJvZHkubWQtYm9keSA+IHRyLm1kLXJvdy5oaWRlYWJsZS1yb3cuaGlkZW1lIHRkIG1kLWNoZWNrYm94IC5tZC1pY29uLFxudGFibGUub3JjaGlkLXRhYmxlIHRhYmxlLm1kLXRhYmxlIHRmb290Lm1kLWZvb3QgPiB0ci5tZC1yb3cuaGlkZWFibGUtcm93LmhpZGVtZSB0ZCBtZC1jaGVja2JveCAubWQtaWNvbiB7XG4gIHdpZHRoOiAwcHg7XG4gIGhlaWdodDogMHB4O1xufVxudGFibGUub3JjaGlkLXRhYmxlIHRib2R5Lm1kLWJvZHkgPiB0ci5tZC1yb3cuaGlkZWFibGUtcm93LmhpZGVtZSB0ZCBtZC1jaGVja2JveCAubWQtY29udGFpbmVyLFxudGFibGUub3JjaGlkLXRhYmxlIHRhYmxlLm1kLXRhYmxlIHRmb290Lm1kLWZvb3QgPiB0ci5tZC1yb3cuaGlkZWFibGUtcm93LmhpZGVtZSB0ZCBtZC1jaGVja2JveCAubWQtY29udGFpbmVyIHtcbiAgd2lkdGg6IDBweDtcbiAgaGVpZ2h0OiAwcHg7XG59XG4iXX0="},{"url":"http://dscott-workstation:81/images/turtle-land.svg","type":"Image","mimeType":"image/svg+xml"},{"url":"http://dscott-workstation:81/service/streams/18/frame?width=414&height=234&now=1550679279208","type":"Image","mimeType":"image/jpeg"},{"url":"http://dscott-workstation:81/service/low-bandwidth/streams/5d8e53f5-9519-48d1-94e2-f26c7587d7b2/frame?1550679278447","type":"Image","mimeType":"application/json","failed":true},{"url":"http://dscott-workstation:81/images/dark_logo.svg","type":"Image","mimeType":"image/svg+xml"},{"url":"http://dscott-workstation:81/images/header_logo.svg","type":"Image","mimeType":"image/svg+xml"},{"url":"http://dscott-workstation:81/fonts-no-cache.css","type":"Stylesheet","mimeType":"text/css"},{"url":"http://dscott-workstation:81/service/streams/24/frame?width=414&height=234&now=1550679278852","type":"Image","mimeType":"image/jpeg"},{"url":"http://dscott-workstation:81/images/toggle-off.svg","type":"Image","mimeType":"image/svg+xml"},{"url":"http://dscott-workstation:81/service/streams/13/frame?width=414&height=234&now=1550679278565","type":"Image","mimeType":"image/jpeg"},{"url":"http://dscott-workstation:81/images/toggle-on.svg","type":"Image","mimeType":"image/svg+xml"},{"url":"http://dscott-workstation:81/fonts/actor-v6-latin-regular.woff2","type":"Font","mimeType":"application/font-woff2"},{"url":"http://dscott-workstation:81/service/streams/9/frame?width=414&height=234&now=1550679278848","type":"Image","mimeType":"image/jpeg"},{"url":"http://dscott-workstation:81/images/playerContainer/resize-south.svg","type":"Image","mimeType":"image/svg+xml"},{"url":"http://dscott-workstation:81/service/streams/5/frame?width=414&height=234&now=1550679278851","type":"Image","mimeType":"image/jpeg"},{"url":"http://dscott-workstation:81/images/playerContainer/resize-east.svg","type":"Image","mimeType":"image/svg+xml"},{"url":"http://dscott-workstation:81/js/vendor-no-cache.js","type":"Script","mimeType":"application/javascript"},{"url":"http://dscott-workstation:81/fonts/fontawesome-webfont.woff2?v=4.7.0","type":"Font","mimeType":"application/font-woff2"},{"url":"http://dscott-workstation:81/css/vendor-no-cache.css","type":"Stylesheet","mimeType":"text/css"},{"url":"http://dscott-workstation:81/images/menu-toggle.svg","type":"Image","mimeType":"image/svg+xml"},{"url":"http://dscott-workstation:81/","type":"Document","mimeType":"text/html"},{"url":"http://dscott-workstation:81/service/streams/2/frame?width=414&height=234&now=1550679278570","type":"Image","mimeType":"image/jpeg"},{"url":"http://dscott-workstation:81/images/playerContainer/resize-southeast.svg","type":"Image","mimeType":"image/svg+xml"},{"url":"http://dscott-workstation:81/js/built-no-cache.js","type":"Script","mimeType":"application/javascript"}]}},"id":4} +28ms
remotedebug sendToTools.{"error":{"code":-32601,"message":"'Profiler' domain was not found","data":[{"code":-32601,"message":"'Profiler' domain was not found"}]},"id":5} +708ms
remotedebug sendToTools.{"result":{},"id":6} +0ms
remotedebug sendToTools.{"method":"Runtime.executionContextCreated","params":{"context":{"id":16,"isPageContext":true,"name":"","origin":"","auxData":{"frameId":"0.1","isDefault":true}}}} +1ms
remotedebug sendToTools.{"method":"Runtime.executionContextCreated","params":{"context":{"id":16,"isPageContext":false,"name":"http://dscott-workstation:81","origin":"http://dscott-workstation:81","auxData":{"frameId":"0.1","isDefault":true}}}} +0ms
remotedebug sendToTools.{"method":"Debugger.scriptParsed","params":{"scriptId":"396","url":"","startLine":0,"startColumn":0,"endLine":3,"endColumn":2}} +5ms

```

Any ideas of what could be causing this and/or how I can provide more information to debug this issue? I'm happy to provide a PR to fix this if someone can point me in the direction of how to solve it.

Thanks.

**Comment by lgp1985** [comment] 2019-04-18 01:57
I included some additional debug info on 2 methods (onMessageFromTarget and onMessageFromTools), and seems everything isn't being understanded anymore from the other end
#138 seems to be the same thing

`C:\Program Files\nodejs\node.exe --inspect-brk=20181 out\index.js
Debugger listening on ws://12
7.0.0.1:20181/01990f7d-f962-431c-93f0-58ab8e499489
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
remotedebug-ios-webkit-adapter is listening on port 9000
New websocket connection to /ios_00008020-001654D214BA002E/ws://127.0.0.1:9101/devtools/page/2
Connection established to ws://127.0.0.1:9101/devtools/page/2
onMessageFromTarget: {"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"page-7","type":"page"}}}
onMessageFromTools: {"id":1,"method":"Network.enable","params":{"maxTotalBufferSize":10000000,"maxResourceBufferSize":5000000}}
onMessageFromTools: {"id":2,"method":"Page.enable"}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Network' domain was not found","data":[{"code":-32601,"message":"'Network' domain was not found"}]},"id":1}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Page' domain was not found","data":[{"code":-32601,"message":"'Page' domain was not found"}]},"id":2}
onMessageFromTools: {"id":3,"method":"Page.getResourceTree"}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Page' domain was not found","data":[{"code":-32601,"message":"'Page' domain was not found"}]},"id":3}
onMessageFromTools: {"id":4,"method":"Profiler.enable"}
onMessageFromTools: {"id":5,"method":"Runtime.enable"}
onMessageFromTools: {"id":6,"method":"Debugger.enable"}
onMessageFromTools: {"id":7,"method":"Debugger.setPauseOnExceptions","params":{"state":"none"}}
onMessageFromTools: {"id":8,"method":"Debugger.setAsyncCallStackDepth","params":{"maxDepth":0}}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Profiler' domain was not found","data":[{"code":-32601,"message":"'Profiler' domain was not found"}]},"id":4}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Runtime' domain was not found","data":[{"code":-32601,"message":"'Runtime' domain was not found"}]},"id":5}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Debugger' domain was not found","data":[{"code":-32601,"message":"'Debugger' domain was not found"}]},"id":-1}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Debugger' domain was not found","data":[{"code":-32601,"message":"'Debugger' domain was not found"}]},"id":6}
(node:4032) UnhandledPromiseRejectionWarning: #<Object>
(node:4032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4032) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
onMessageFromTools: {"id":9,"method":"DOM.enable"}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Debugger' domain was not found","data":[{"code":-32601,"message":"'Debugger' domain was not found"}]},"id":7}
onMessageFromTools: {"id":10,"method":"CSS.enable"}
onMessageFromTools: {"id":11,"method":"Log.enable"}
onMessageFromTarget: {"error":{"code":-32601,"message":"'CSS' domain was not found","data":[{"code":-32601,"message":"'CSS' domain was not found"}]},"id":10}
onMessageFromTools: {"id":12,"method":"Log.startViolationsReport","params":{"config":[{"name":"longTask","threshold":200},{"name":"longLayout","threshold":30},{"name":"blockedEvent","threshold":100},{"name":"blockedParser","threshold":-1},{"name":"handler","threshold":150},{"name":"recurringHandler","threshold":50},{"name":"discouragedAPIUse","threshold":-1}]}}
onMessageFromTools: {"id":13,"method":"ServiceWorker.enable"}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Console' domain was not found","data":[{"code":-32601,"message":"'Console' domain was not found"}]},"id":11}
onMessageFromTools: {"id":14,"method":"Target.setAutoAttach","params":{"autoAttach":true,"waitForDebuggerOnStart":true}}
onMessageFromTools: {"id":15,"method":"Target.setRemoteLocations","params":{"locations":[{"host":"localhost","port":9229}]}}
onMessageFromTools: {"id":16,"method":"Target.setDiscoverTargets","params":{"discover":true}}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Log' domain was not found","data":[{"code":-32601,"message":"'Log' domain was not found"}]},"id":12}
onMessageFromTarget: {"error":{"code":-32601,"message":"'ServiceWorker' domain was not found","data":[{"code":-32601,"message":"'ServiceWorker' domain was not found"}]},"id":13}
onMessageFromTools: {"id":17,"method":"Page.setAutoAttachToCreatedPages","params":{"autoAttach":false}}
onMessageFromTools: {"id":18,"method":"Emulation.setScriptExecutionDisabled","params":{"value":false}}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Target.setAutoAttach' was not found","data":[{"code":-32601,"message":"'Target.setAutoAttach' was not found"}]},"id":14}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Target.setRemoteLocations' was not found","data":[{"code":-32601,"message":"'Target.setRemoteLocations' was not found"}]},"id":15}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Target.setDiscoverTargets' was not found","data":[{"code":-32601,"message":"'Target.setDiscoverTargets' was not found"}]},"id":16}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Page' domain was not found","data":[{"code":-32601,"message":"'Page' domain was not found"}]},"id":17}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Page' domain was not found","data":[{"code":-32601,"message":"'Page' domain was not found"}]},"id":18}
onMessageFromTools: {"id":19,"method":"Rendering.setShowViewportSizeOnResize","params":{"show":true}}
onMessageFromTools: {"id":20,"method":"Inspector.enable"}
onMessageFromTools: {"id":21,"method":"Debugger.setBlackboxPatterns","params":{"patterns":[]}}
onMessageFromTools: {"id":22,"method":"Page.getNavigationHistory"}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Rendering' domain was not found","data":[{"code":-32601,"message":"'Rendering' domain was not found"}]},"id":19}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Inspector' domain was not found","data":[{"code":-32601,"message":"'Inspector' domain was not found"}]},"id":20}
onMessageFromTools: {"id":23,"method":"Page.startScreencast","params":{"format":"jpeg","quality":80,"maxWidth":1128,"maxHeight":584}}
onMessageFromTools: {"id":24,"method":"Page.addScriptToEvaluateOnLoad","params":{"scriptSource":"(function(){const touchEvents=['ontouchstart','ontouchend','ontouchmove','ontouchcancel'];var recepients=[window.__proto__,document.__proto__];for(var i=0;i<touchEvents.length;++i){for(var j=0;j<recepients.length;++j){if(!(touchEvents[i]in recepients[j])){Object.defineProperty(recepients[j],touchEvents[i],{value:null,writable:true,configurable:true,enumerable:true});}}}})()"}}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Runtime' domain was not found","data":[{"code":-32601,"message":"'Runtime' domain was not found"}]},"id":-2}
(node:4032) UnhandledPromiseRejectionWarning: #<Object>
(node:4032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
onMessageFromTarget: {"error":{"code":-32601,"message":"'Runtime' domain was not found","data":[{"code":-32601,"message":"'Runtime' domain was not found"}]},"id":-3}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Page' domain was not found","data":[{"code":-32601,"message":"'Page' domain was not found"}]},"id":24}
(node:4032) UnhandledPromiseRejectionWarning: #<Object>
(node:4032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
onMessageFromTools: {"id":25,"method":"Emulation.setTouchEmulationEnabled","params":{"enabled":true,"configuration":"mobile"}}
onMessageFromTools: {"id":26,"method":"Page.stopScreencast"}
onMessageFromTools: {"id":27,"method":"Emulation.setTouchEmulationEnabled","params":{"enabled":false,"configuration":"desktop"}}
onMessageFromTools: {"id":28,"method":"Runtime.runIfWaitingForDebugger"}
onMessageFromTools: {"id":29,"method":"Page.startScreencast","params":{"format":"jpeg","quality":80,"maxWidth":408,"maxHeight":584}}
onMessageFromTools: {"id":30,"method":"Page.addScriptToEvaluateOnLoad","params":{"scriptSource":"(function(){const touchEvents=['ontouchstart','ontouchend','ontouchmove','ontouchcancel'];var recepients=[window.__proto__,document.__proto__];for(var i=0;i<touchEvents.length;++i){for(var j=0;j<recepients.length;++j){if(!(touchEvents[i]in recepients[j])){Object.defineProperty(recepients[j],touchEvents[i],{value:null,writable:true,configurable:true,enumerable:true});}}}})()"}}
onMessageFromTools: {"id":31,"method":"Emulation.setTouchEmulationEnabled","params":{"enabled":true,"configuration":"mobile"}}
onMessageFromTools: {"id":32,"method":"Page.stopScreencast"}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Page' domain was not found","data":[{"code":-32601,"message":"'Page' domain was not found"}]},"id":25}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Page' domain was not found","data":[{"code":-32601,"message":"'Page' domain was not found"}]},"id":27}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Runtime' domain was not found","data":[{"code":-32601,"message":"'Runtime' domain was not found"}]},"id":28}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Runtime' domain was not found","data":[{"code":-32601,"message":"'Runtime' domain was not found"}]},"id":-4}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Page' domain was not found","data":[{"code":-32601,"message":"'Page' domain was not found"}]},"id":30}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Page' domain was not found","data":[{"code":-32601,"message":"'Page' domain was not found"}]},"id":31}
(node:4032) UnhandledPromiseRejectionWarning: #<Object>
(node:4032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
onMessageFromTools: {"id":33,"method":"Emulation.setTouchEmulationEnabled","params":{"enabled":false,"configuration":"desktop"}}
onMessageFromTools: {"id":34,"method":"Page.startScreencast","params":{"format":"jpeg","quality":80,"maxWidth":408,"maxHeight":584}}
onMessageFromTools: {"id":35,"method":"Page.addScriptToEvaluateOnLoad","params":{"scriptSource":"(function(){const touchEvents=['ontouchstart','ontouchend','ontouchmove','ontouchcancel'];var recepients=[window.__proto__,document.__proto__];for(var i=0;i<touchEvents.length;++i){for(var j=0;j<recepients.length;++j){if(!(touchEvents[i]in recepients[j])){Object.defineProperty(recepients[j],touchEvents[i],{value:null,writable:true,configurable:true,enumerable:true});}}}})()"}}
onMessageFromTools: {"id":36,"method":"Emulation.setTouchEmulationEnabled","params":{"enabled":true,"configuration":"mobile"}}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Page' domain was not found","data":[{"code":-32601,"message":"'Page' domain was not found"}]},"id":33}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Runtime' domain was not found","data":[{"code":-32601,"message":"'Runtime' domain was not found"}]},"id":-5}
(node:4032) UnhandledPromiseRejectionWarning: #<Object>
(node:4032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
onMessageFromTarget: {"error":{"code":-32601,"message":"'Page' domain was not found","data":[{"code":-32601,"message":"'Page' domain was not found"}]},"id":35}
onMessageFromTarget: {"error":{"code":-32601,"message":"'Page' domain was not found","data":[{"code":-32601,"message":"'Page' domain was not found"}]},"id":36}
`

**Comment by antimatter96** [comment] 2019-04-24 08:27
@lgp1985  Can you add these lines
```js
process.on('uncaughtException', (error) => {
  coneole.error("Uncaught exception", error);
});
process.on('unhandledRejection', (reason, p) => {
  console.log('Unhandled Rejection at:', p, 'reason:', reason);
});
```
in your start script to capture the missing errors ?
Also what ios version, chrome version are you using ?

**Comment by auchenberg** [comment] 2021-03-29 04:20
Duplicate of https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/69

**Closed as completed by auchenberg** 2021-03-29 04:20 UTC
