### ISSUE TITLE
Remote target #LOCALHOST has nothing

### ISSUE THREAD

**Issue by dajiaoyisheng** [RemoteDebug/remotedebug-ios-webkit-adapter#118] opened 2018-10-22 09:11 UTC
> Chrome:// inspect /#devices
> Remote target #LOCALHOST

 has nothing, but cmd keeps outputting iosAdapter.getTargets, where is the problem?

**Comment by sandcastle** [comment] 2018-10-22 22:41
I'm seeing the same issue, just a constant stream of `iosAdapter.getTargets` messages.

When I run in debug mode, I can see the following:

```
DEBUG=remotedebug  remotedebug_ios_webkit_adapter --port=9001
  remotedebug server.run, port=9001 +0ms
  remotedebug server.setupHttpHandlers +4ms
  remotedebug iOSAdapter.getProxySettings +5ms
  remotedebug iOSAdapter.getProxyPath +0ms
  remotedebug adapterCollection.start Map {} +3ms
  remotedebug adapter.start { port: 9101,
  proxyExePath: '/usr/local/bin/ios_webkit_debug_proxy',
  proxyExeArgs: [ '--no-frontend', '--config=null:9101,:9102-9202' ],
  pollingInterval: 3000,
  baseUrl: 'http://127.0.0.1',
  path: '/json' } +1ms
  remotedebug adapter.spawnProcess, path=/usr/local/bin/ios_webkit_debug_proxy +1ms
  remotedebug server.http.endpoint/json/version +187ms
  remotedebug server.http.endpoint/json +5ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug server.startTargetFetcher +13ms
remotedebug-ios-webkit-adapter is listening on port 9001
  remotedebug adapter.spawnProcess.stderr, data=Could not connect to lockdownd, error code -19. Exiting.
  remotedebug  +79ms
  remotedebug adapter.spawnProcess.stderr, data=Unable to attach a20ff548fa1a1e96ac3389b5d452b957d8701e19 inspector
  remotedebug  +0ms
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +1ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +1ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +1ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +1ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getTargets +896ms
iosAdapter.getTargets
  remotedebug server.startTargetFetcher.fetched.0 +2ms
  remotedebug server.http.endpoint/json/version +105ms
  remotedebug server.http.endpoint/json +1ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +0ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
```

**Comment by sandcastle** [comment] 2018-10-22 22:43
Looks like a duplicate of #107

**Comment by auchenberg** [comment] 2018-10-23 02:47
Closing as dup

**Closed as completed by auchenberg** 2018-10-23 02:47 UTC
