### ISSUE TITLE
Windows not able to inspect iOS 11

### ISSUE THREAD

**Issue by taneltm** [RemoteDebug/remotedebug-ios-webkit-adapter#79] opened 2017-10-18 08:49 UTC
The issue is of course that the bundled ios-webkit- debug-proxy-win32 doesn't support it.
I installed this https://github.com/google/ios-webkit-debug-proxy then modified iosAdapter.js to use that instead of the bundled version under vs-libimobile - that way I was able to get the debugging to work!

But remotedebug_ios_webkit_adapter keeps logging an error while getting the device version:
```
...
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
New websocket connection to /ios_116146f0a7fea095bc5254fa3a1b35ec07699c7f/PID:433
Connection established to ws://127.0.0.1:9101/devtools/page/1
iosAdapter.getTargets
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
...
```

I'm guessing it's unable to get the version of the device from ```node_modules/vs-libimobile/lib/ideviceinfo.exe```, when I run that directly, it says:
```
socket_receive_timeout: fd=456 recv returned 0
ERROR: Could not connect to lockdownd, error code -3
```

**Comment by bdice** [comment] 2017-12-13 18:02
I finally got it to work with a lot of failed attempts. Here were my steps for any future users attempting to do the same. I am running Windows 10 with iOS 11 on my device.

1. Following from [this StackOverflow post](https://stackoverflow.com/questions/20408110/debug-ipad-safari-with-a-pc), I installed Node, iTunes, and enabled web inspector on my iPad (Settings > Safari > Advanced). Using Powershell as administrator, install the remote debugger: `npm install remotedebug-ios-webkit-adapter -g` I attempted to run the adapter: `remotedebug_ios_webkit_adapter --port=9000`. I saw `iosAdapter.getTargets` over and over, but the page at `chrome://inspect/#devices` didn't show any remote targets at port 9000. (This is a recreation of the problem).

Now is the part where I try to make the edit for iOS 11.

2. Download the latest release of https://github.com/google/ios-webkit-debug-proxy/. No need to install scoop. Just get the zip release. I grabbed version 1.8: https://github.com/google/ios-webkit-debug-proxy/releases/download/v1.8/ios-webkit-debug-proxy-1.8-win64-bin.zip

3. Unzip that release. I chose to put it in the same folder as the broken library (to make the edit easier), in `%AppData%\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\vs-libimobile\ios-webkit-debug-proxy-1.8-win64-bin`

4. Edit the file `%AppData%\npm\node_modules\remotedebug-ios-webkit-adapter\out\adapters\iosAdapter.js`. On line 132, it reads:
`const proxy = path.resolve(__dirname, '../../node_modules/vs-libimobile/lib/ios_webkit_debug_proxy.exe');`
Change this location to point to the location of the `ios_webkit_debug_proxy.exe` you unzipped earlier. I changed this line to say:
`const proxy = path.resolve(__dirname, '../../node_modules/vs-libimobile/ios-webkit-debug-proxy-1.8-win64-bin/ios_webkit_debug_proxy.exe');`

Now try to run again:

5. Re-open Chrome to `chrome://inspect/#devices` and run PowerShell as an administrator. Run `remotedebug_ios_webkit_adapter --port=9000` and make sure Chrome is configured to search for a network target on that port (Discover Network Targets > Configure). Open Safari on your iPad. Hopefully this works.

I also had to unplug and re-plug my iPad before this would work. It appeared Windows hadn't yet configured the drivers properly. I can confirm that I also see the repeated error message mentioned by @taneltm  above. Seeing this message may be a good confirmation that things _should_ be working.
```
...
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
...
```

**Comment by mohamedmansour** [comment] 2018-01-25 06:10
@bdice  this worked great! We should merge that 1.8v in!

**Comment by auchenberg** [comment] 2018-01-25 19:13
@bdice @mohamedmansour Any of you interested in becoming maintainer? I simply don't have the time. My thinking is that a similar approach on Windows to how do we install `ios-webkit-debug-proxy` via a dependency manager needs to happen Windows, as the currently VS NPM package is way out of date.

**Comment by HaykoKoryun** [comment] 2018-02-02 20:53
@bdice you are a lifesaver!

**Comment by fadupla** [comment] 2018-03-29 14:17
Many thanks @bdice !

**Comment by auchenberg** [comment] 2018-03-29 16:24
@taneltm @bdice @HaykoKoryun @fadupla PRs for updating this are more than welcome. I don't have the bandwidth these days!

**Comment by JoeMeeks** [comment] 2018-04-09 21:15
@auchenberg @bdice @taneltm I have a PR ready:
https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/pull/91

**Comment by Prinzhorn** [comment] 2018-04-24 12:46
I'm slightly confused as I have the exact same symptoms on Ubuntu. However, for Mac/Linux the code uses the installed binary and not the one shipped with vs-libimobile.

```js
else if (os.platform() === 'darwin' || os.platform() === 'linux') {
    which('ios_webkit_debug_proxy', function (err, resolvedPath) {
        if (err) {
            reject('ios_webkit_debug_proxy not found. Please install ios_webkit_debug_proxy (https://github.com/google/ios-webkit-debug-proxy)');
        }
        else {
            resolve(resolvedPath);
        }
    });
}
```

If In understand @bdice correctly the issue was resolved by using a more recent version of the ios_webkit_debug_proxy binary. But I have the most recent one installed and it successfully connects to my iPad when used directly.

```
$ ios_webkit_debug_proxy 
Listing devices on :9221
Connected :9222 to iPad (....)
```

However, running the adapter I get the exact symptoms described here

```
$ DEBUG=remotedebug remotedebug_ios_webkit_adapter
  remotedebug server.run, port=9000 +0ms
  remotedebug server.setupHttpHandlers +3ms
  remotedebug iOSAdapter.getProxySettings +2ms
  remotedebug iOSAdapter.getProxyPath +1ms
  remotedebug adapterCollection.start Map {} +13ms
  remotedebug adapter.start { port: 9100,
  proxyExePath: '/usr/local/bin/ios_webkit_debug_proxy',
  proxyExeArgs: [ '--no-frontend', '--config=null:9100,:9101-9201' ],
  pollingInterval: 3000,
  baseUrl: 'http://127.0.0.1',
  path: '/json' } +1ms
  remotedebug adapter.spawnProcess, path=/usr/local/bin/ios_webkit_debug_proxy +1ms
  remotedebug server.startTargetFetcher +206ms
remotedebug-ios-webkit-adapter is listening on port 9000
  remotedebug server.http.endpoint/json/version +192ms
  remotedebug server.http.endpoint/json +17ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getDeviceVersion +19ms
  remotedebug iOSAdapter.getDeviceInfoPath +0ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.start { port: 9101,
  pollingInterval: 3000,
  baseUrl: 'http://127.0.0.1',
  path: '/json' } +2ms
  remotedebug adapter.start: Skip spawnProcess, no proxyExePath available +0ms
  remotedebug adapter.getTargets, metadata=[object Object] +0ms
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +1ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getDeviceVersion +4ms
  remotedebug iOSAdapter.getDeviceInfoPath +1ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.getTargets, metadata=[object Object] +2ms
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +1ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getDeviceVersion +4ms
  remotedebug iOSAdapter.getDeviceInfoPath +0ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.getTargets, metadata=[object Object] +2ms
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +1ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getDeviceVersion +3ms
  remotedebug iOSAdapter.getDeviceInfoPath +0ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.getTargets, metadata=[object Object] +3ms
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +1ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getDeviceVersion +2ms
  remotedebug iOSAdapter.getDeviceInfoPath +0ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.getTargets, metadata=[object Object] +1ms
  remotedebug iOSAdapter.getTargets +718ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getDeviceVersion +3ms
  remotedebug iOSAdapter.getDeviceInfoPath +1ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.getTargets, metadata=[object Object] +2ms
  remotedebug server.startTargetFetcher.fetched.0 +2ms
  remotedebug server.http.endpoint/json/version +278ms
  remotedebug server.http.endpoint/json +1ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getDeviceVersion +3ms
  remotedebug iOSAdapter.getDeviceInfoPath +0ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.getTargets, metadata=[object Object] +2ms
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +1ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getDeviceVersion +3ms
  remotedebug iOSAdapter.getDeviceInfoPath +0ms
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
  remotedebug adapter.getTargets, metadata=[object Object] +1ms
  remotedebug server.stop +930ms
  remotedebug server.stopTargetFetcher +1ms
  remotedebug adapterCollection.stop +1ms
  remotedebug adapter.stop +0ms
  remotedebug adapter.stop +1ms
```

**Comment by shard2001** [comment] 2018-05-04 12:56
If you're behind a company proxy then in adapter.js and iosAdapter.js change

request(this._url)

to

request({'url':this._url, 'proxy': ''}

**Comment by johnsheldon** [comment] 2018-06-08 20:13
I have tried all the steps above including using release 1.8 of ios-webkit-debug-proxy. However, I'm still having an issue when I start on port 9000 and fetching no targets:

```remotedebug_ios_webkit_adapter
remotedebug server.run, port=9000 +0ms
  remotedebug server.setupHttpHandlers +0ms
  remotedebug iOSAdapter.getProxySettings +15ms
  remotedebug iOSAdapter.getProxyPath +0ms
  remotedebug adapterCollection.start Map {} +0ms
  remotedebug adapter.start { port: 9100,
  proxyExePath: 'C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\remotedebug-ios-webkit-adapter\\node_modules\\vs-libimobile\\x64\\ios_webkit_debug_proxy.exe',
  proxyExeArgs: [ '--no-frontend', '--config=null:9100,:9101-9201' ],
  pollingInterval: 3000,
  baseUrl: 'http://127.0.0.1',
  path: '/json' } +0ms
  remotedebug adapter.spawnProcess, path=C:\Users\username\AppData\Roaming\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\vs-libimobile\x64\ios_webkit_debug_proxy.exe +0ms
  remotedebug adapter.spawnProcess.stderr, data=Could not connect to lockdownd. Exiting.: No error
  remotedebug  +110ms
  remotedebug server.http.endpoint/json +15ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug server.http.endpoint/json/version +31ms
  remotedebug server.startTargetFetcher +78ms
remotedebug-ios-webkit-adapter is listening on port 9000
  remotedebug server.http.endpoint/json/version +3s
  remotedebug server.http.endpoint/json +0ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getTargets +2s
iosAdapter.getTargets
  remotedebug server.startTargetFetcher.fetched.0 +0ms
  remotedebug server.http.endpoint/json/version +2s
  remotedebug server.http.endpoint/json +16ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getTargets +3s
iosAdapter.getTargets
  remotedebug server.startTargetFetcher.fetched.0 +0ms
  remotedebug server.http.endpoint/json/version +1s
  remotedebug server.http.endpoint/json +15ms
  remotedebug iOSAdapter.getTargets +0ms
iosAdapter.getTargets
  remotedebug iOSAdapter.getTargets +4s```

**Comment by generalov** [comment] 2018-11-16 10:45
Thanks, @bdice! Your receipt still works in 2018. :)
```
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
```
This error message caused by vs-libimobile package that provides an outdated version of libimobiledevice library.

I downloaded latest version from https://www.nuget.org/packages/libimobiledevice/ and extracted it to the root of a project. I also changed path to `ideviceinfo.exe` in `node_modules\remotedebug-ios-webkit-adapter\out\adapters\iosAdapter.js` :
```
// const proxy = path.resolve(__dirname, process.env.USERPROFILE + '/AppData/Roaming/npm/node_modules/vs-libimobile/lib/ideviceinfo.exe');
const proxy = path.resolve("imobiledevice-x64-1.2.1-r223\\ideviceinfo.exe");
```
It prevents the error message. It is also safe to remove vs-libimobile from dependencies.

**Comment by auchenberg** [comment] 2018-11-21 19:54
@generalov Great insight. We need to find a way to download `ideviceinfo.exe` from a package manager on Windows or something like this. Are you aware of way to install globally via Nuget? Alternatively we could add `libimobiledevice` to scoop?

**Comment by generalov** [comment] 2018-11-23 08:55
Hi @auchenberg, I'm not happy with external dependencies like scoop, Nuget and hardcoded paths to executables. It would be nice to have dependencies installed locally using npm package manager.

If npm does not provide enough functionality then what's about [selenium-standalone](https://www.npmjs.com/package/selenium-standalone)'s approach? It provides `install` command for end users to install all necessary binaries into local node_modules folder.

**Comment by auchenberg** [comment] 2018-11-23 18:03
@generalov I'm not a big fan either, but I don't want to distribute binaries with this project. On Linux/MacOS we leverage existing package managers where the binaries for dependencies are published and it works great. 

Windows is the troublesome platform, and we had `ios-webkit-debug-proxy` publish it's binaries via scoop. The challenge is that theres no official windows builds of `libimobiledevice` being published, and I don't want to be in the business of maintaining such things.

**Comment by HarelM** [comment] 2019-01-27 18:59
I'm following the instructions on the readme and here but still unable to debug chrome on my iPad.
Has anyone managed to do it recently?

**Comment by HarelM** [comment] 2019-01-27 20:33
Sorry, the problem was that I needed to add the relevant port to chrome dev tools...

**Comment by B-Stewart** [comment] 2019-02-28 21:01
@generalov I know it's been a while but what release did you download to get the .exe? Between the nupkg and release .zips I can't find anything I can download that has `ideviceinfo.exe` bundled in it.

**Comment by devonzara** [comment] 2019-02-28 23:14
@B-Stewart download the `ios-webkit-debug-proxy-1.8.3-win64-bin.zip` from https://github.com/google/ios-webkit-debug-proxy/releases to find the executable.

That said, I'm having difficulties getting it to work. I modified `iosAdapter.js` to point to the executable from the Google release but it's still showing the error below over and over and no connection is appearing in Chrome.
```
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
```

**Edit**
After closing Chrome and all of my console windows, opening them again, and restarting the adapter; it worked. The screencast of the device lagged and crashed the Chrome tab several times but once I disabled that, it was smooth sailing.

**Comment by acalvino4** [comment] 2019-04-11 17:42
> I finally got it to work with a lot of failed attempts. Here were my steps for any future users attempting to do the same. I am running Windows 10 with iOS 11 on my device.
> 
> 1. Following from [this StackOverflow post](https://stackoverflow.com/questions/20408110/debug-ipad-safari-with-a-pc), I installed Node, iTunes, and enabled web inspector on my iPad (Settings > Safari > Advanced). Using Powershell as administrator, install the remote debugger: `npm install remotedebug-ios-webkit-adapter -g` I attempted to run the adapter: `remotedebug_ios_webkit_adapter --port=9000`. I saw `iosAdapter.getTargets` over and over, but the page at `chrome://inspect/#devices` didn't show any remote targets at port 9000. (This is a recreation of the problem).
> 
> Now is the part where I try to make the edit for iOS 11.
> 
> 1. Download the latest release of https://github.com/google/ios-webkit-debug-proxy/. No need to install scoop. Just get the zip release. I grabbed version 1.8: https://github.com/google/ios-webkit-debug-proxy/releases/download/v1.8/ios-webkit-debug-proxy-1.8-win64-bin.zip
> 2. Unzip that release. I chose to put it in the same folder as the broken library (to make the edit easier), in `%AppData%\npm\node_modules\remotedebug-ios-webkit-adapter\node_modules\vs-libimobile\ios-webkit-debug-proxy-1.8-win64-bin`
> 3. Edit the file `%AppData%\npm\node_modules\remotedebug-ios-webkit-adapter\out\adapters\iosAdapter.js`. On line 132, it reads:
>    `const proxy = path.resolve(__dirname, '../../node_modules/vs-libimobile/lib/ios_webkit_debug_proxy.exe');`
>    Change this location to point to the location of the `ios_webkit_debug_proxy.exe` you unzipped earlier. I changed this line to say:
>    `const proxy = path.resolve(__dirname, '../../node_modules/vs-libimobile/ios-webkit-debug-proxy-1.8-win64-bin/ios_webkit_debug_proxy.exe');`
> 
> Now try to run again:
> 
> 1. Re-open Chrome to `chrome://inspect/#devices` and run PowerShell as an administrator. Run `remotedebug_ios_webkit_adapter --port=9000` and make sure Chrome is configured to search for a network target on that port (Discover Network Targets > Configure). Open Safari on your iPad. Hopefully this works.
> 
> I also had to unplug and re-plug my iPad before this would work. It appeared Windows hadn't yet configured the drivers properly. I can confirm that I also see the repeated error message mentioned by @taneltm above. Seeing this message may be a good confirmation that things _should_ be working.
> 
> ```
> ...
> iosAdapter.getTargets
> error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
> iosAdapter.getTargets
> error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
> iosAdapter.getTargets
> error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
> ...
> ```

The repository mentioned,  https://github.com/google/ios-webkit-debug-proxy/ , has no file named ios_webkit_debug_proxy.exe, yet we are instructed to change line 132 of iosAdapter.js to point to it's location.   Am I missing something, or has this repository changed, or are these bad instructions?

**Comment by bdice** [comment] 2019-04-11 17:56
@acalvino4 Try downloading a release with a binary, it's not in the repository itself: https://github.com/google/ios-webkit-debug-proxy/releases

**Comment by acalvino4** [comment] 2019-04-11 18:58
Alright, found the right release (1.8.3) and followed all instructions on this thread (including shutting down all terminals and browsers, and unplugging/replugging my device as some have suggested), but I'm still getting the same error, and chrome://inspect/#devices is not showing any remote target (yes, I've added localhost:9000 to Discover network targets > Configure).

The only thing I notice that is different on my system from the solution posted is that the install path differs slightly from what @bdice has:
1. I have Roaming in the directory tree between AppData and npm -> AppData/Roaming/npm/...
2. Under the second node-modules folder, there is no vs-libimobile folder, which leads me to believe I missed installing something.  

To install I had done:

scoop bucket add extras
scoop install ios-webkit-debug-proxy
npm install -g vs-libimobile
npm install remotedebug-ios-webkit-adapter -g

all in Administrator Power Shell, with success messages, as directed [here](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter).

**Comment by AusQB** [comment] 2019-04-23 01:53
I was able to get it running to the point where my remote target shows up in DevTools (without having to perform @bdice's workaround), but when I click inspect nothing shows up in the inspector window. Powershell just keeps repeating the same messages he mentioned at the bottom of his post. This is on an 8 Plus running iOS 12.2.

**Comment by MrBearTW** [comment] 2019-04-26 07:19
> I was able to get it running to the point where my remote target shows up in DevTools (without having to perform @bdice's workaround), but when I click inspect nothing shows up in the inspector window. Powershell just keeps repeating the same messages he mentioned at the bottom of his post. This is on an 8 Plus running iOS 12.2.

I have the same problem, when I click inspect nothing shows up in the inspector window.
It has a warning "Consider disabling Chrome Data Server while debugging" in  inspector window, I disable it , but it's still nothing shows up.
I am using Win10 with ios-webkit-debug-proxy(v1.8.4) and iPhone X.

**Comment by ghost** [comment] 2019-06-11 11:06
anyone? I'm using X and win 10, but like @MrBearTW, i can see device and tabs, but without content

**Comment by fsiliadin** [comment] 2019-06-11 15:01
I Have the same problem as @dzbiku  and @MrBearTW. Maybe it's because the protocols are not up to date with recent ios versions? I can see that in the protocols folders we only have ios, ios8 and ios9, with ios 9 file as default value. Can you please provide insights to adapt this to latest ios versions?

**Comment by crewone** [comment] 2019-06-26 12:48
I have the same as @MrBearTW , @dzbiku  and @fsiliadin . Changing the path doesn't fix it.

**Comment by JenkaJmenka** [comment] 2019-07-29 09:30
unfortunately I have the same issue. Following the instructions above didn't solve my problem.

**Comment by mjpoo** [comment] 2019-09-01 16:02
I am getting the following error as documented by @generalov above.

```
iosAdapter.getTargets
error.iosAdapter.getTargets.getDeviceVersion.failed.fallback, device=[object Object]
```

I understand that I need to install the libimobiledevice `ideviceinfo.exe` file but I cannot find it in any repos. Please can someone point me to this.

**Comment by mafsays** [comment] 2019-09-02 08:06
@mikejpoole I can't get this to work at the moment but worth pointing out that when I did have it up and running, getting this error was an indication that the device was connected successfully, if I didn't get that error it meant it wasn't working! So worth checking your browser for the device despite the error.

**Comment by mjpoo** [comment] 2019-09-06 14:18
Thanks @mafsays . I did not realise that it was not an error message. I am now getting a "Unhandled promise rejection" errors. Is that also what is not working for you at the moment. I believe that is being dealt with in issue 138 with some PR's waiting to be merged to hopefully fix that.

**Comment by okandas** [comment] 2019-09-11 07:25
also try `remotedebug_ios_webkit_adapter --port=9222` for ios .... Worked for me on ios 11.

**Comment by carpben** [comment] 2019-10-02 18:22
Maybe we can change the title to "Windows not able to inspect iOS 11 + "

**Comment by carpben** [comment] 2019-10-03 04:58
This issue has been opened two years ago, for IOS 11. Two years later, and two IOS versions later, the issue has still not been resolved. 
However, the documentation still represents the library as a solution for debugging IOS Safari from Windows. I suggest updateing the documentation to make it as clear as possible that this solution doesn’t currently work. 
Installing this tool on Windows isn’t trivial (it requires 4 installations), so presenting this info before hand can save valuable time to other programmers. 
@taneltm @bdice

**Comment by dimitar-nikovski** [comment] 2019-10-17 13:42
The instructions provided by @bdice worked a charm in iOS 11, but updating to 13.1.3 causes the same errors as encountered by the OP

**Comment by carpben** [comment] 2019-10-17 15:55
I really appreciate the contribution of the library and the contributors. However, it has been two weeks since I wrote https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/79#issuecomment-537786808, and two years since this issue was originally opened. 

Currently 
- This solution doesn't work for modern IOS for 2 years. 
- The documentation presents the library as a working solution for debugging IOS on Windows. 
- As a result developers install 4 separate installations and to invest their time for a solution we already know doesn't work. 

We must update documentation and notify users about this limitation. I'll submit a suggestion.  
@auchenberg @JoeMeeks @taneltm @vaskevich @skrat @qkdreyer @paulirish @pandreyn @ninjaonsafari @kriserickson @gogoprog  @elitree @cmaraglio  @benzhe @arilotter @Sardtok @OliverJAsh @AamuLumi

**Comment by auchenberg** [comment] 2019-10-17 18:47
@carpben This project is currently unmaintained. If you are interested in becoming an maintainer and taking a lead on this effort let me know.

**Comment by carpben** [comment] 2019-10-18 04:41
Thanks @auchenberg, Unfortunately, proffesionally I'm not the right person for this mission. I don't have experience or expertise in the relevant fields.

**Comment by bmtheo** [comment] 2019-10-31 10:06
Just to make sure I understand - this package is not working (even with @bdice workaround) with iOS 12+ ?
And as of today there is no other solution to make it work ?

**Comment by carpben** [comment] 2019-11-05 18:04
Yes @bmtheo, this is correct.

**Comment by IAMtheIAM** [comment] 2019-11-21 18:53
Note: I didn't have to do any of the extra steps from @bdice in https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/79#issuecomment-351472710 to get it working for iOS 11. I just following the instructions on the readme, and it worked right away.

**Comment by kofifus** [comment] 2020-10-19 22:25
I followed the instructions here https://washamdev.com/debug-a-website-in-ios-safari-on-windows/ including the ones for ios 11 and with itunes opened and it works with my ipad on ios 14 (!)

**Comment by lawjww** [comment] 2021-02-02 17:34
Can somebody please walk me through the ios11 one. I got lost at the part when he explained about extracting and editing the files. Seriously, its too complicated. Need Your Help ! ASAP.. SOS

**Comment by Csabbencs** [comment] 2021-03-25 09:10
Hi, I'm stuck at step 6 of the above instruction webpage,
I can see "remotedebug-ios-webkit-adapter is listening on port 9000" only but no "iosAdapter.getTargets" following that.
http://localhost:9000/ says {"msg":"Hello from RemoteDebug iOS WebKit Adapter"}.
https://inspect/#devices does not load.
Can you advise?

**Comment by auchenberg** [comment] 2021-03-29 04:10
This project is now super-seeded by https://inspect.dev/ – a new developer tool for macOS and Windows to inspect and debug your web apps and websites in Safari and WebViews on iOS devices.

RemoteDebug iOS WebKit Adapter is not proactively maintained or extended.

**Closed as completed by auchenberg** 2021-03-29 04:10 UTC
Labels: help wanted
