### ISSUE TITLE
Working with Simulator?

### ISSUE THREAD

**Issue by ekulabuhov** [RemoteDebug/remotedebug-ios-webkit-adapter#46] opened 2017-02-15 17:12 UTC
Hi! I wonder if it works with Simulator? I've tried with iOS 10 Simulator and I see an empty list browsing to /json endpoint.

**Comment by auchenberg** [comment] 2017-02-20 00:14
It should be. The simulator has to be started before the adapter is started, due to a limitation in `ios-webkit-debug-proxy`.

What happens if you start ios-webkit-debug-proxy directly?

**Comment by ekulabuhov** [comment] 2017-02-20 13:30
This is likely related to: https://github.com/google/ios-webkit-debug-proxy/issues/185

I dug a bit deeper and it seems like `/json` on `ios-webkit-debug-proxy` is returning an empty list. At this point I'm quite certain that the problem is not related to this project. Thanks!

Simulator version: iOS 10.2 (14C89).

**Comment by artygus** [comment] 2017-02-20 13:39
duplicate of #185

**Comment by auchenberg** [comment] 2017-02-21 04:25
Closing as https://github.com/google/ios-webkit-debug-proxy/issues/185 is closed.

**Closed as completed by auchenberg** 2017-02-21 04:25 UTC
