### ISSUE TITLE
Devices not shown Window 10 in chrome

### ISSUE THREAD

**Issue by wclr** [RemoteDebug/remotedebug-ios-webkit-adapter#146] opened 2019-05-24 15:31 UTC
Running
```
remotedebug_ios_webkit_adapter --port=9000
```

http://127.0.0.1:9100/json shows 
```
[
{
deviceId: "bfd49856bc3b5bdd1e5c54829bd80154d06ad6dc",
deviceName: "iPad",
url: "127.0.0.1:9101"
}
]
```

But no devices in chrome://inspect

Safari opened, trusted (shown in iTunes), web inspector enable.

**Comment by MarventusWP** [comment] 2019-06-03 23:48
I'm facing exact same issue. Navigating to when I try to open http://localhost:9101, I get the following:

> Inspectable pages for **{myDeviceName}**:

No pages are actually being listed.

**Comment by MarventusWP** [comment] 2019-06-03 23:58
I did a little research on the current Open issues, and the most likely cause is issue https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/138.

For me, it's definitely 12.2 since I upgraded iOS recently to 12.3.1.

**Comment by ewanharris** [comment] 2020-01-02 14:09
I believe this to be a duplicate of #138. Please open a new issue if the issue still persists when using the latest prerelease, which can be obtained via `npm i -g remotedebug-ios-webkit-adapter@next`

**Closed as completed by ewanharris** 2020-01-02 14:09 UTC
