### ISSUE TITLE
Perfermance cannot be opend on Mac with Chrome

### ISSUE THREAD

**Issue by TyhGB** [RemoteDebug/remotedebug-ios-webkit-adapter#201] opened 2020-09-10 07:47 UTC
When i use 'chrome://inspect' to inspect webview in iPhone, the perfermance cannot be opend.
The Chrome is blocked at initializing Profiler. Below is the Picture.
![image](https://user-images.githubusercontent.com/30275349/92696724-e0b9f900-f37c-11ea-8285-be38788a937d.png)

**Comment by auchenberg** [comment] 2021-03-29 04:20
Duplicate of https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/69

**Closed as completed by auchenberg** 2021-03-29 04:20 UTC
