### ISSUE TITLE
Not show url in chrome devtools.

### ISSUE THREAD

**Issue by mrdulin** [RemoteDebug/remotedebug-ios-webkit-adapter#84] opened 2017-11-21 05:49 UTC
![image](https://user-images.githubusercontent.com/17866683/33056793-88e33c6e-cec2-11e7-8ef3-1921e214eaaf.png)
![image](https://user-images.githubusercontent.com/17866683/33056806-9fab46f8-cec2-11e7-9bc9-a36b6a972b88.png)

IOS 11.0
latest tools

**Comment by auchenberg** [comment] 2017-11-27 22:22
@mrdulin Are you on Windows? Could be a duplicate of https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/79

**Comment by mrdulin** [comment] 2017-11-28 04:01
@auchenberg Mac OSX

**Comment by auchenberg** [comment] 2017-11-28 05:13
Can you then please provide a few more details about your setup, so a helpful person could try to reproduce the error you have having.

**Comment by auchenberg** [comment] 2018-01-17 00:36
Closing due to in activity.

**Closed as completed by auchenberg** 2018-01-17 00:36 UTC

**Comment by mrdulin** [comment] 2018-01-23 10:25
@auchenberg I just follow the guide: https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter#getting-started

But my google chrome is not Canary version. Is it the reason?

-- update --

chrome canary is not the reason. chrome official version is ok.

**Comment by ibraalek10** [comment] 2018-01-24 16:26
Hello, i have same problem of @mrdulin..
"Chrome Inspect" don't recognize my Iphone and therefore i can't do debug of my webapp on chrome iOs..
Someone can help me?
Thanks

**Comment by mrdulin** [comment] 2018-01-25 03:15
@ibraalek10 

try these:
1. turn on iPhone safari web inspector 
2. connect your phone use USB
3. open your OSX safari - develop - a dialog will popup in your phone - trust your computer 
4. use chrome://inspect, make sure your browser/pc network proxy is ok.

**Comment by ibraalek10** [comment] 2018-01-26 09:54
@mrdulin 
Thanks for response..
I tried it but i have same problem.. 
On Safari iOs with Safari Mac OsX, debug works very well..
But chrome://inspect doesn't recognize chrome on my iPhone..
This is a screen: 
![schermata 2018-01-26 alle 10 50 46](https://user-images.githubusercontent.com/23355148/35434386-3e20a1e6-0287-11e8-9470-47ba23f4c79a.png)

Can you help me?
Thanks a lot

Alessio

**Comment by mrdulin** [comment] 2018-01-26 15:56
@ibraalek10 Sorry. I just successfully use this to let chrome://inspect debug page in iPhone Safari. 

For page in webview of hybird app, I have the same issue. even if I build a debug app, not release app.

the document give less information about this.

**Comment by johnjudeh** [comment] 2018-02-25 22:18
Hi, I know this thread is closed but I am having the same issue on macOS with connecting my iPhone. The ios-webkit-debug-proxy connects fine but when I try the remotedebug-ios-webkit-adapter after following all the steps in the README.md, I get the same repeating message in my terminal of iosAdapter.getTargets and my Chrome Dev Tools does not see my device. The web inspector on safari is also working so I am not sure what the problem is! Any help would be greatly appreciated :)

**Comment by avennn** [comment] 2018-07-12 08:04
Sorry to report here I still have the problem now.

**Comment by StephanieDover** [comment] 2018-07-12 17:20
I'm having the same issue. I followed the instructions for getting it running on a mac, and went to chrome://inspect/#devices and it's not showing my device. I did allow inspect in the phone's safari settings and have it connected to me computer. I got this running and it's just repeating "iosAdapter.getTargets" in the terminal.

**Comment by adsl99801** [comment] 2019-01-17 10:26
ios_webkit_debug_proxy -f chrome-devtools://devtools/bundled/inspector.html
Listing devices on :9221
Abort trap: 6

$ remotedebug_ios_webkit_adapter --port=9000
remotedebug-ios-webkit-adapter failed to run with the following error: adapter.spawnProcess.close, code=null
